### ISSUE TITLE
Команда красных

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/summer_java_practice_2019#24]
# Текущие проблемы (вечер 7 июля)

## Общего характера
- [x] Отсутствует диаграмма классов
- [ ] team.md не заполнен совсем

## Проблемы исходного кода
Код в текущем виде компилируется, UI отображается. Тем не менее, нету методов, решающих поставленную задачу на логическом уровне (алгоритм), визуализация в процессе реализации, судя по всему (результат drag'n'drop-а вершины):
![2019-07-07-221031_590x370_scrot](https://user-images.githubusercontent.com/7635910/60772839-afa0c180-a104-11e9-96f7-b94b3ccc0c53.png)

Таким образом:
- [ ] Требуется реализовать pom.xml и привести структуру проекта к общему виду, используя архетипы Maven (рекомендуется quickstart archetype http://maven.apache.org/archetypes/maven-archetype-quickstart/)
- [x] Требуется реализовать алгоритм задачи на уже реализованном графе.
- [ ] Добавить JUnit в зависимости Maven и добавить модульные тесты для структуры графа (создание, добавление/удаление вершины/ребра) и самого алгоритма. 
- [ ] (опционально, но желательно) озаботиться работой с внешними ресурсами, такими как файлы с данными для работы программы. Примеры входных данных должны быть в репозитории вместе с собранным jar-архивом (см. README про конечную структуру директории проекта). Кроме того, вы можете использовать эти же файлы с данными для автоматизации тестирования, задавая входные данные тестов при помощи файлов.
- [ ] (опционально, но желательно) Поправьте Task и About, раз уж они есть.
- [x] Исправить и закончить отрисовку графа
- [x] Реализовать отображение решения на графе (без пошагового выполнения).

Сосредоточьтесь на этих задачах. Как только они будут выполнены - я напишу дальнейший список.

**Comment by JAkutenshi** [comment]
# Этап 2

- [ ] Перенести кнопку Start вниз
- [ ] Индекс текущего шага (текущий/всего), поле защищено от записи
- [ ] Если Start не нажата - кнопки шагов не должны работать.
- [ ] Если графа нет (Clear graph), то вообще кнопки не должны быть доступны, индекс очищен.
- [ ] Добавить кнопки "Перейти в самое начало" и "Перейти в самый конец"
- [ ] Добавить кнопкам иконки

**Comment by BaturinIgor** [comment]
Обязательно ли нужно собирать проект через терминал? У меня сам проект собирается через maven без каких-либо ошибок, проходят все тесты и удачно создается .jar. Если сборка проекта через терминал обязательно, подскажите как это сделать, выдает такие ошибки:
![image](https://user-images.githubusercontent.com/31727456/60992856-081acd80-a356-11e9-9298-b730dba667c9.png)
